### ISSUE TITLE
The documentation disappeared and it looks weird on CPAN

### ISSUE THREAD

**Issue by smonff** [awncorp/faker#24]
It looks like since last `1.04` release, all the modules documentations disappeared, from a CPAN point of view. It is an issue because it's possible that people would read the module documentation from CPAN. It was previously fine until `1.03`.

I am not sure what happened, since I don't know how you release modules, maybe your authoring tool did something bad, or you decided to just maintain documentation in the README files? Something seems to be not in it's right state.

The whole distribution looks weird on CPAN, since the modules have zero line of POD, not even the required sections like NAME, AUTHOR, LICENSE, etc.

Just saying, in case you didn't know... If there is anything I can do I would help, but I am not sure to understand what happened here.

**Comment by iamalnewkirk** [comment]
@smonff Thanks, and sorry for the slow reply. I'm pretty sure this is the result of a CI/CD process run amok. I'll fix this within the next day or so.

**Comment by awncorp** [comment]
@smonff Fwiw, I've release a new version of the library, v1.23, which has a new architecture, still tiny, plus support for I18N with En-Us, Es-Es, and Ja-Jp built-in.
