### ISSUE TITLE
Tests have started to fail

### ISSUE THREAD

**Issue by andk** [awncorp/faker#26]
Sample fail report: http://www.cpantesters.org/cpan/report/ccd6e06a-2c96-11ed-aa2e-d130e6deb7e4

I could replicate this on perl 5 36.0 by first installing Venus 1.23, then Faker 1.10. This gave a PASS report. Then installing Venus 1.30, then testing Faker 1.10 again. This gave a FAIL report.

**Comment by iamalnewkirk** [comment]
Resolved by https://github.com/awncorp/faker/releases/tag/1.15.

**Comment by awncorp** [comment]
Resolved by https://github.com/awncorp/faker/releases/tag/1.17.
